# datasource
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:statesdb
    username: sa
    password:

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  # h2
  h2:
    console.enabled: true
    console.path: /h2
